# Generated by Django 4.2.1 on 2023-05-24 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0105_edit_generic_device_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='variable name'),
        ),
    ]
